<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Behavioral Data Dcience
email: althoff@cs.washinton.edu
description: > # this means to ignore newlines until "baseurl:"
  Behavioral Data Science @ UW CSE.
baseurl: ""
url: ""


RESOURCES_PATH: resources
include:
  - .htaccess
  - _pages

collections:
  - people
  - publications
  - pubpdfs

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

=======
name: Behavioral Data Science
collections:
  - publications
  - pubpdfs
  - people

RESOURCES_PATH: ./resources
# Could add individual pages for each pub pretty easily using output : true
>>>>>>> 5f7ea909ece63556f404588fb2803597781ac010
